// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl0hwiwCcZOjVX_Cu6ruBo6TZ5mKf4-S4',
    appId: '1:709301713682:web:8e96ba3b1f625b596951cb',
    messagingSenderId: '709301713682',
    projectId: 'fitnessapp-e1e07',
    authDomain: 'fitnessapp-e1e07.firebaseapp.com',
    storageBucket: 'fitnessapp-e1e07.firebasestorage.app',
    measurementId: 'G-ZMR1VQGKLY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmFzBQ8DNTpCzXfE46PMHv8PckpSpyVl4',
    appId: '1:709301713682:android:cf2351eb86247f626951cb',
    messagingSenderId: '709301713682',
    projectId: 'fitnessapp-e1e07',
    storageBucket: 'fitnessapp-e1e07.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz3ACUAwps42M4NHr-sxrv4Kys2PhwsYU',
    appId: '1:709301713682:ios:87b3dcd27f11661c6951cb',
    messagingSenderId: '709301713682',
    projectId: 'fitnessapp-e1e07',
    storageBucket: 'fitnessapp-e1e07.firebasestorage.app',
    iosBundleId: 'com.example.finallapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz3ACUAwps42M4NHr-sxrv4Kys2PhwsYU',
    appId: '1:709301713682:ios:87b3dcd27f11661c6951cb',
    messagingSenderId: '709301713682',
    projectId: 'fitnessapp-e1e07',
    storageBucket: 'fitnessapp-e1e07.firebasestorage.app',
    iosBundleId: 'com.example.finallapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDl0hwiwCcZOjVX_Cu6ruBo6TZ5mKf4-S4',
    appId: '1:709301713682:web:f505b19a8cfa3d836951cb',
    messagingSenderId: '709301713682',
    projectId: 'fitnessapp-e1e07',
    authDomain: 'fitnessapp-e1e07.firebaseapp.com',
    storageBucket: 'fitnessapp-e1e07.firebasestorage.app',
    measurementId: 'G-3FD8Z6NETV',
  );
}
